name: Deploy to Firebase
on:
  push:
    branches:
      - master
  schedule:
    # GHAはUTC基準なので、JST換算すると毎朝午前4時
    - cron: '0 19 * * *'
env:
  TZ: Asia/Tokyo
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CLI_EXPERIMENTS: webframeworks
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      QIITA_API_KEY: ${{ secrets.QIITA_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - name: Make .env
        run: echo QIITA_API_KEY=${{ secrets.QIITA_API_KEY }} > .env
      - uses: actions/cache@v4 # https://github.com/cypress-io/github-action/tree/v4.2.2#install-cypress-only
        id: node_modules_cache_id
        with:
          path: node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: npm ci
      - name: Make Article Data
        run: npm run make:data
      - name: Build
        run: npm run build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      # 認証情報を保持するjsonファイルをGOOGLE_APPLICATION_CREDENTIALSで指定したpassに生成
      - name: make GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting
      # 作成されたデータファイルを保存
      - name: Check Diff
        id: check_diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit
        if: steps.check_diff.outcome == 'failure'
        # メールアドレスの設定についてはこちらを参照
        # https://github.com/kokoroe-dev/kokoroe-frontend/pull/734#discussion_r1484925218
        run: |
          git config user.name "actions-user"
          git config user.email "action@github.com"
          git add .
          git commit -m "Make Articles & GitHub Contributions Data"
          git push origin ${{ github.head_ref }}