name: Deploy to Firebase
on:
  push:
    branches:
      - master
env:
  TZ: Asia/Tokyo
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
      QIITA_API_KEY: ${{ secrets.QIITA_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - name: Check env
        run: env
      - uses: actions/cache@v4 # https://github.com/cypress-io/github-action/tree/v4.2.2#install-cypress-only
        id: node_modules_cache_id
        with:
          path: node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: npm ci
      - name: Make Article Data
        run: npm run make:data
      - name: Build
        run: npm run build
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting --token $FIREBASE_DEPLOY_TOKEN